---
title: "File Identification"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{File Identification}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

The most natural way to identify a file is by its **name**. The Drive API, however, fundamentally identifies a file by its unique id. googledrive makes it easy to specify your file of interest by name at first, but then immediately capture that in a way that includes the file's id. This facilitates downstream file operations.

googledrive holds information on Drive files in what we call a **dribble**, a Drive tibble. A [tibble](http://tibble.tidyverse.org/reference/tibble.html) is the variant of the data frame that is used throughout the [tidyverse](http://www.tidyverse.org). A googledrive dribble will have one row per file and is guaranteed to have these variables:

  * `name`: The file's name.
  * `id`: The file's unique id.
  * `drive_resource`: A list column containing Drive API metadata that is internally useful and possibly interesting to some users. The typical user will leave this variable unexamined. Just let it be.
  
Some functions add additional variables, but the three above are always present. `drive_reveal()`, for example, can add file paths, MIME types, trash status, and information about permissions and publishing. Use your usual techniques for data frame manipulation in order to isolate specific rows -- files, in this case -- that you want to operate on. For example, you can manipulate the dribble with dplyr verbs such as `filter()`, `mutate()`, `arrange()`, and `slice()`.

## How to get one or more files in a dribble

How do you get files into a dribble in the first place? Two main functions for this:

  * `drive_find()`: Similar to <drive.google.com>. Lists all your files or lets you narrow things down based on name or file properties.
  * `drive_get()`: Get files by name -- file path, actually -- or by id, including by URL.
  
## `drive_find()`

Read the help for complete documentation but here are some of the many ways to call `drive_find()`:

```{r eval = FALSE}
drive_find()
drive_find(n_max = 40)
drive_find(pattern = "chicken")
drive_find(type = "pdf")
drive_find(type = "folder")
drive_find(type = "spreadsheet")
drive_find(trashed = TRUE)
drive_find(q = "fullText contains 'horsebean'")
drive_find(q = "modifiedTime > '2017-07-21T12:00:00'", order_by = "recency")
drive_find(q = c("starred = true", "visibility = 'anyoneWithLink'"))
```

## `drive_get()`

*to be written*

## Other functions to get or manage a dribble

  * `drive_reveal()`
  * `drive_ls()`
  * `drive_browse()`
