---
title: "Map Demo"
author: "Lucy D’Agostino McGowan"
date: "5/5/2017"
output: 
  github_document:
    toc: true
---

```{r, message = FALSE, warning = FALSE}
library("dplyr")
library("googledrive")
```

## grab a file
```{r}
my_file <- drive_get_id("test") %>%
  drive_file
```

## lets take a peak
```{r}
my_file
```


## we can also pull out multiple files
```{r}
lst_of_files <- purrr::map(.x =drive_get_id("test", n = 3), drive_file) 
```

## change access
```{r}
my_file <- my_file %>%
  drive_share(role = "reader", type = "anyone")
```

## check access
```{r}
my_file
```

## upload one
```{r}
drive_upload("~/desktop/hide/test.txt", "This is a test")
```

## upload to a specific folder
```{r}
drive_ls()
```

I'll use my `THIS IS A TEST` folder.

```{r}
folder <- drive_get_id("THIS IS A TEST") %>%
  drive_file
```


```{r}
new_file <- drive_upload("~/desktop/hide/test.txt") %>%
  drive_mv(folder)
```

## delete a lot!

```{r}
to_delete <- purrr::map(drive_get_id("test", n = 3),  drive_file)
 
purrr::map(to_delete, drive_delete)
```

